spring.application.name=gestion-biblioteca

# URL de conexion: localhost, puerto 5432, base: biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca

# Usuario de PostgreSQL
spring.datasource.username=postgres

# Contrasena de PostgreSQL
spring.datasource.password=titu59316pt

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Indica a Hibernate que actualice la estructura de la BD automaticamente
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false


# Puerto opcional
server.port=8080

